allows specifying the link_section for a map
redsift/redbpf pull request #107
Opened 2020-11-13 15:29 UTC by kbknapp

This commit changes the `map` attribute macro to allow specifying a section
name manually, or using the item name when explict names are omitted.

For example, the *old* version:

```rust
static mut counts: PerfMap<u64> = PerfMap::with_max_entries(10240);
```

Would place the map in the `maps/counts` section of the resulting ELF
binary. Note the repetition of the names.

The new style infers the name from the item:

```rust
static mut counts: PerfMap<u64> = PerfMap::with_max_entries(10240);
```

Which still places the map in the `maps/counts` section of the binary.

However, in some cases the default naming scheme does not work (such as
in `tc` BPF programs). If the link section must be supplied manually,
one can use this method:

```rust
static mut counts: PerfMap<u64> = PerfMap::with_max_entries(10240);
```

In this case the map will be placed in the explicit `foo` section of the
binary.

Closes #105

2020-11-16 08:56 UTC, alessandrod requested changes
This looks ok but it breaks the current API so it can't be merged until we release 2.x. 

In order to merge it now it needs to be changed to still support the old `#[map("literal")]` form, and we should somehow output a deprecation warning when the old form is used.

2020-11-16 16:14 UTC, kbknapp commented
Sounds good, I can add that later today.

2020-11-17 15:28 UTC, rsdy approved these changes

2020-11-17 15:28 UTC, rsdy commented
I'm super happy with this. Really good quality code! Thanks!

2020-11-17 15:29 UTC, merged