Skips re-run of build.rs if C source doesnt change
redsift/redbpf pull request #115
Opened 2020-12-03 21:13 UTC by kbknapp

This commit tells `cargo` not to run the `build.rs` scripts in the
following crates if the specified C source files have not changed:

- `redbpf-probes`
- `bpf-sys`
- `redbpf-tools`
- `redbpf-tools/probes`

Prior to this commit `cargo` would re-run the build scripts (which are
generating language bindings to C libraries) on each compile/check. This
drastically slows down the dev cycle, especially if editors want to run
checks after each change/save.

On my desktop Threadripper 2950 (16 cores) with an NVMe drive, the time
spent generating bindings on *every* build was roughly 91 seconds in
debug mode in the worst case. But even cutting out the outlier 
(`redbpf-tools(/probes)`), each crate would be in the 8 second range which 
is still high for certain editors which re-run checks constantly.

This change cuts that wait time out entirely unless the C source files
change.

2020-12-04 05:49 UTC, alessandrod requested changes
The direction is good but I think that most file systems won't update the mtime of a directory when something inside it changes. I think we need to glob and print one line for each file.

2020-12-04 05:49 UTC, alessandrod commented on bpf-sys/build.rs
I don't think `rerun-if-changed=directory/` does the right thing, see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-changedpath

2020-12-04 05:49 UTC, alessandrod commented on redbpf-tools/build.rs
> +    println!("cargo:rerun-if-changed=probes/");
This is unnecessary, at the bottom we're already printing a rerun-if-changed for each probe file

2020-12-04 21:34 UTC, kbknapp commented
Great points, I'll make the changes later today once I get to a computer.

2020-12-05 03:06 UTC, kbknapp commented
Changes have been made. Let me know if you see something else that should change :wink:

2020-12-05 03:15 UTC, alessandrod approved these changes
Thank you! Looks good now.

2020-12-05 12:31 UTC, merged